# Overlays: private directories laid out like this repo's root, which this repo's tooling reads
# from as well as from itself. A machine lists its overlays in ai/secrets/machine.local.psd1
# (git-ignored), so no tracked file here ever names one. See ai/secrets/README.md.
#
# What an overlay may carry, each at the same path as in this repo:
#   ai/secrets/registry.psd1 + ai/secrets/<Id>/   skill secrets; registries merge
#   aws/config                                    at most one source across repo and overlays
#   git/gitconfig                                 a fragment; every overlay's is included
#   ai/skills/<name>/                             skills, linked by ai/install.sh; a name ships from one place
#   bruno/<collection>/                           Bruno collections, linked into ~/bruno by ai/install.sh; a name ships from one place

# Whether a machine.local.psd1 opts the machine into skill secrets: it must declare SearchRoots,
# which deploy-secrets.ps1 cannot run without. The file alone is not enough, because a machine
# also writes it just to list OptionalTools or Overlays. A declared but empty SearchRoots still
# opts in, so deploy-secrets.ps1 reports it rather than the sync skipping it in silence.
function Test-SkillSecretsOptIn {
    param([Parameter(Mandatory)][string]$LocalPath)

    if (-not (Test-Path -LiteralPath $LocalPath)) { return $false }
    return (Import-PowerShellDataFile $LocalPath).ContainsKey('SearchRoots')
}

# The overlay directories listed in a machine.local.psd1. No file, or no Overlays key, is no
# overlays. A listed directory that does not exist is an error: silently skipping it would
# quietly drop every secret and setting it carries.
function Get-OverlayList {
    param([Parameter(Mandatory)][string]$LocalPath)

    if (-not (Test-Path -LiteralPath $LocalPath)) { return @() }
    $local = Import-PowerShellDataFile $LocalPath
    if (-not $local.Overlays) { return @() }

    foreach ($dir in $local.Overlays) {
        if (-not (Test-Path -LiteralPath $dir -PathType Container)) {
            throw "overlay '$dir' listed in $LocalPath does not exist"
        }
    }
    return @($local.Overlays)
}

# Every skill in the ai/secrets/registry.psd1 of each root, in order, each with the SecretsDir its
# encrypted files live in. A root without a registry contributes nothing. The same Id in two
# roots is an error naming both, because either answer would be a guess.
function Get-MergedSkillRegistry {
    param([Parameter(Mandatory)][string[]]$Roots)

    $seen = @{}
    foreach ($root in $Roots) {
        $registryPath = Join-Path $root "ai\secrets\registry.psd1"
        if (-not (Test-Path -LiteralPath $registryPath)) { continue }

        foreach ($skill in (Import-PowerShellDataFile $registryPath).Skills) {
            if ($seen.ContainsKey($skill.Id)) {
                throw "skill '$($skill.Id)' is registered in both $($seen[$skill.Id]) and $registryPath"
            }
            $seen[$skill.Id] = $registryPath

            $entry = $skill.Clone()
            $entry.SecretsDir = Join-Path $root "ai\secrets\$($skill.Id)"
            $entry
        }
    }
}

# The one root that provides RelativePath, or $null when none does. More than one is an error
# naming them all: a file linked to a single target cannot come from two places.
function Find-OverlayFile {
    param(
        [Parameter(Mandatory)][string[]]$Roots,
        [Parameter(Mandatory)][string]$RelativePath
    )

    $found = @($Roots |
        ForEach-Object { Join-Path $_ $RelativePath } |
        Where-Object { Test-Path -LiteralPath $_ -PathType Leaf })
    if ($found.Count -gt 1) {
        throw "$RelativePath is provided by more than one source: $($found -join ', ')"
    }
    if ($found.Count -eq 1) { return $found[0] }
    return $null
}

# The contents of ~/.gitconfig-overlays: one include per overlay that ships git/gitconfig, in
# overlay order, so a later overlay overrides an earlier one.
function Get-GitOverlayIncludeContent {
    param([string[]]$Overlays = @())

    $lines = @("# Generated by powershell/setup.ps1 from the Overlays in ai/secrets/machine.local.psd1. Do not edit.")
    foreach ($overlay in $Overlays) {
        $fragment = Join-Path $overlay "git\gitconfig"
        if (Test-Path -LiteralPath $fragment -PathType Leaf) {
            $lines += "[include]"
            $lines += "`tpath = $($fragment -replace '\\', '/')"
        }
    }
    return ($lines -join "`n") + "`n"
}

# The distinct git repositories the overlays live in, in the order first listed, so each is
# pulled once however many overlays it holds. An overlay outside any repository has nothing to
# pull and is left out.
function Get-OverlayRepoRoots {
    param([string[]]$Overlays = @())

    $roots = [ordered]@{}
    foreach ($overlay in $Overlays) {
        # try/catch, not just 2>$null: under $ErrorActionPreference = 'Stop', PowerShell 5.1
        # turns a native command's stderr into a terminating error.
        try { $top = git -C $overlay rev-parse --show-toplevel 2>$null } catch { $top = $null }
        if ($LASTEXITCODE -ne 0 -or -not $top) { continue }
        $top = [IO.Path]::GetFullPath($top)
        if (-not $roots.Contains($top)) { $roots[$top] = $true }
    }
    return @($roots.Keys)
}

# Writes the Overlays entry of a machine.local.psd1, replacing the one there or adding one before
# the closing brace. The rest of the file, comments included, is left as it was. An Overlays entry
# this cannot recognise is an error rather than a guess.
function Set-OverlayListInFile {
    param(
        [Parameter(Mandatory)][string]$LocalPath,
        [string[]]$Overlays = @()
    )

    $text = [IO.File]::ReadAllText($LocalPath)
    $nl = if ($text -match "`r`n") { "`r`n" } else { "`n" }
    $items = @($Overlays | ForEach-Object { "        '$($_ -replace "'", "''")'" })
    $entry = if ($items.Count) { "Overlays = @($nl$($items -join $nl)$nl    )" } else { "Overlays = @()" }

    $found = [regex]::Matches($text, "(?m)^[ \t]*Overlays\s*=\s*@\((\s*'(?:[^']|'')*'\s*,?)*\s*\)")
    if ($found.Count -gt 1) { throw "$LocalPath has more than one Overlays entry; edit it by hand" }
    if ($found.Count -eq 1) {
        $m = $found[0]
        $indent = [regex]::Match($m.Value, '^[ \t]*').Value
        $text = $text.Substring(0, $m.Index) + $indent + $entry + $text.Substring($m.Index + $m.Length)
    } else {
        if ((Import-PowerShellDataFile $LocalPath).ContainsKey('Overlays')) {
            throw "$LocalPath has an Overlays entry this cannot rewrite; edit it by hand"
        }
        $close = $text.LastIndexOf('}')
        if ($close -lt 0) { throw "$LocalPath has no closing brace" }
        $text = $text.Substring(0, $close).TrimEnd() + "$nl$nl    $entry$nl}" + $text.Substring($close + 1)
    }
    [IO.File]::WriteAllText($LocalPath, $text)
}

# Brings ~/.gitconfig-overlays in line with the overlays. Returns 'AlreadyCorrect', 'Written', or
# with -Check 'WouldWrite' and changes nothing.
function Update-GitOverlayInclude {
    param(
        [string[]]$Overlays = @(),
        [string]$Path = "$env:USERPROFILE\.gitconfig-overlays",
        [switch]$Check
    )

    $content = Get-GitOverlayIncludeContent -Overlays $Overlays
    if ((Test-Path -LiteralPath $Path) -and ([IO.File]::ReadAllText($Path) -eq $content)) { return 'AlreadyCorrect' }
    if ($Check) { return 'WouldWrite' }
    # WriteAllText writes UTF-8 without a BOM; Set-Content in PowerShell 5.1 cannot.
    [IO.File]::WriteAllText($Path, $content)
    return 'Written'
}
